// <auto-generated />
namespace PointOfSaleManagement.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class model_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(model_change));
        
        string IMigrationMetadata.Id
        {
            get { return "201908050650363_model_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
